# preston >

counta = 0
counta = int(counta)
countb = 0
countb = int(countb)

Str = "abbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaabababababababaabababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbababa"



# print(f"The amount of 'a's in the string is: )
# print(f"The amount of 'b's in the string is: )