# preston >

counta = 0
counta = int(counta)
countb = 0
countb = int(countb)

Str = "abbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaabababababababaabababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbababa"

